--Hiiii all of this code is from me, no ai used! i just
--wanted to add comments for readability!

--why do i feel like i need to make my comments silly to make them sound like they werent generated by ai TwT

--this lib should work with other lua engines as long as they have delta time i think
local anim={}

function anim.new(frames,duration,type,endfunc) --if you want to use this do something like myAnim=anim.new({1,2,3},150,"loop")
    local a={
        frames=frames, --all of the animation frames
        duration=duration, --how long each frame is displayed in milliseconds
        type=type, --the type of animation, can be loop, random, noloop, or pingpong
        frame=1, --the current frame
        time=0, --the animations internal time
        dir=1, --you can ignore this, its just for the pingpong animation system,
        endfunc=endfunc,
        ranfunc=false
    }
    if type=="loop" then
        a.update=function(self,dt)
            self.time=self.time+dt*1000 --stole this from my tiled system :3
            if self.time>=duration then
                self.frame=self.frame+1
                self.time=0 --reset time
                if self.frame>#self.frames then
                    self.frame=1 --reset the frame
                end
            end
        end
    elseif type=="random" then
        a.update=function(self,dt)
            self.time=self.time+dt*1000 --stole this from my loop function :3
            if self.time>=duration then
                local p=self.frame --i think you know what this does
                while self.frame==p do
                    self.frame=math.random(#self.frames) --set the current frame to a random one
                end
                self.time=0 --i have no idea why i put this here now
            end
        end
    elseif type=="noloop" then
        a.update=function(self,dt)
            self.time=self.time+dt*1000 --stole this from my random function :3
            if self.time>=duration and self.frame<#self.frames then --make sure the frame isnt at the end of the animation
                self.frame=self.frame+1
                self.time=0
            elseif not self.ranfunc then
                self.ranfunc=true
                if self.endfunc then self.endfunc() end
            end
        end
    elseif type=="pingpong" then
        a.update=function(self,dt)
            self.time=self.time+dt*1000 --stole this from my noloop function :3
            if self.time>=duration then
                self.frame=self.frame+self.dir --change the frame by the direction of the animation
                self.time=0
                if self.frame>=#self.frames then --i could've probably made this a little cleaner but my brain is too smooth
                    self.dir=-1
                elseif self.frame<=1 then
                    self.dir=1
                end
            end
        end
    end
    a.reset=function(self) --pretty much for the noloop animation type, not too fancy.
        self.time=0
        self.frame=1
        self.ranfunc=false
    end
    a.get=function(self) --use this in your draw call like gfx.spr(myAnim:get(),0,0)
        return self.frames[self.frame]+1
    end
    return a
end

return anim --does anyone else forget to add this?